name: publish

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish_wiki:
    name: Publish to Wiki
    runs-on: ubuntu-20.04
    env:
      WIKI_TMPDIR: "wiki_tmp"
    steps:
      - name: Set PR Number Envar
        run: |
          echo "PR_NUMBER=$(jq --raw-output .pull_request.number $GITHUB_EVENT_PATH)" >> $GITHUB_ENV
          echo "PR_MD_FILEPATH=${WIKI_TMPDIR}/PR_${{ env.PR_NUMBER }}_${GITHUB_RUN_ID}.md" >> $GITHUB_ENV

      - name: Generate something
        if: github.event_name == 'pull_request'
        run: |
          mkdir "${WIKI_TMPDIR}"

          #PR_MD_FILEPATH="${WIKI_TMPDIR}/PR_${{env.PR_NUMBER}}_${GITHUB_RUN_ID}.md"

          echo "${{ env.PR_MD_FILEPATH }}"

          echo '```' >> "${{ env.PR_MD_FILEPATH }}"
          echo "some other content all together again" >> "${{ env.PR_MD_FILEPATH}}"
          echo '```' >> "${{ env.PR_MD_FILEPATH}}"
      
      - name: Publish output to wiki
        uses: docker://decathlon/wiki-page-creator-action:2.0.3
        env:
          GH_PAT: ${{ secrets.GHPAT }}
          ACTION_MAIL: ${{ secrets.GHEMAIL }}
          ACTION_NAME: ${{ github.repository_owner }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          MD_FOLDER: "wiki_tmp/"

      - name: cat test
        run: |
          #PR_MD_FILEPATH="${WIKI_TMPDIR}/PR_${{env.PR_NUMBER}}_${GITHUB_RUN_ID}.md"

          cat ${{ env.PR_MD_FILEPATH }}
