name: publish

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish_wiki:
    name: Publish to Wiki
    runs-on: ubuntu-20.04
    steps:
      - name: Generate something
        if: github.event_name == 'pull_request'
        run: |
          mkdir wikitmp

          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          
          pr_md_filepath="wiki/PR_${PR_NUMBER}_${GITHUB_RUN_ID}.md"

          echo "${pr_md_filepath}"

          echo '```' >> "wiki_tmp/${pr_md_filepath}"
          echo "some other content all together" >> "wiki_tmp/{pr_md_filepath}"
          echo '```' >> "wiki_tmp/${pr_md_filepath}"
      
      - name: Publish output to wiki
        uses: docker://decathlon/wiki-page-creator-action:2.0.3
        env:
          GH_PAT: ${{ secrets.GHPAT }}
          ACTION_MAIL: ${{ secrets.GHEMAIL }}
          ACTION_NAME: ${{ github.repository_owner }}
          OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          MD_FOLDER: "wiki_tmp/"
