name: publish

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  publish_wiki:
    name: Publish to Wiki
    runs-on: ubuntu-20.04
    steps:
      - name: Create publish dir
        run: mkdir wiki

      - name: Generate something
        run: |
          echo "# Heading 2" > "wiki/pr.md"
          echo '```' >> "wiki/pr.md"
          echo "some content" >> "wiki/pr.md"
          echo '```' >> "wiki/pr.md"
      
      - name: Sync docs to wiki
        uses: Andrew-Chen-Wang/github-wiki-action@v3
        env:
          # Make sure you have that / at the end. We use rsync 
          # WIKI_DIR's default is wiki/
          WIKI_DIR: "wiki/"
          GH_TOKEN: ${{ secrets.GHPAT }}
          GH_MAIL: ${{ secrets.GHEMAIL }}
          GH_NAME: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}
          WIKI_PUSH_MESSAGE: "commit"
